- name: "Copy over the keystore"
  copy:
    src: "{{ keystore_path }}"
    dest: /home/ubuntu/cert/{{ keystore_path | basename }}
    mode: '0440'
    owner: "ubuntu"
    group: "ubuntu"
  when: keystore_path is defined
