prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: consul
        metrics_path: /v1/agent/metrics
        params:
          format: [prometheus]
          help: [yes]
        scrape_interval: 30s
        scrape_timeout:  10s
        consul_sd_configs:
          - server:   consul.service.consul:8500
            datacenter: us-east-1
            services: [consul]
            allow_stale: true
            refresh_interval: 5m
        relabel_configs:
          - source_labels: [__meta_consul_service]
            regex:         (.*)
            target_label:  job
            replacement:   $1
          - source_labels: [__meta_consul_node]
            regex:         (.*)
            target_label:  instance
            replacement:   $1
          - source_labels: [__address__]
            separator:     ':'
            regex:         (.*):(8300)
            target_label:  __address__
            replacement:   ${1}:8500

      - job_name: host-prometheus
        metrics_path: /metrics
        scrape_interval: 10s
        scrape_timeout:  10s
        consul_sd_configs:
          - server:   consul.service.consul:8500
            datacenter: us-east-1
            services: [consul_node_exporter]
            allow_stale: true
            refresh_interval: 5m
        relabel_configs:
          - source_labels: [__meta_consul_service]
            regex:         (.*)
            target_label:  job
            replacement:   $1
          - source_labels: [__meta_consul_service_id]
            regex:         (.*)
            target_label:  instance
            replacement:   $1
          - source_labels: [__meta_consul_tags]
            regex:         ((?:[a-z][a-z]+))
            target_label:  service
            replacement:   $1