name: "c3"
stack:
  - "us-east-1/network/vpc-mgmt"
  - "us-east-1/network/peering-main-logging"
  - "us-east-1/network/peering-mgmt"
  - "us-east-1/logging/elasticsearch-sg"
  - "us-east-1/logging/elasticsearch"