#!/usr/bin/env bash

DIRECTORIES=( \
#"global/audit/s3-cloudtrail" \
#"global/audit/cloudtrail" \
#"us-east-1/logging/log-config-bucket" \
#"us-east-1/logging/lb-logging-bucket" \
#"us-east-1/data" \
#"us-east-1/network/vpc-main" \
#"us-east-1/network/vpc-mgmt" \
#"us-east-1/network/vpc-support" \
#"us-east-1/network/vpc-services" \
#"us-east-1/network/peering-main" \
#"us-east-1/network/peering-mgmt-services" \
#"us-east-1/network/peering-mgmt-support" \
#"us-east-1/network/peering-support-services" \
#"us-east-1/network/dns" \
#"us-east-1/bastion/keys-bucket" \
#"us-east-1/bastion/keys" \
#"us-east-1/bastion/iam" \
#"us-east-1/bastion/sg" \
"us-east-1/bastion/ec2" \
#"us-east-1/bastion/dns" \
#"us-east-1/services/ecr" \
#"us-east-1/services/sg" \
#"us-east-1/services/eks" \
#"us-east-1/consul/keys" \
#"us-east-1/consul/packer" \
#"us-east-1/consul/ec2" \
#"us-east-1/consul/dns" \
#"us-east-1/citizen/keys" \
#"us-east-1/citizen/iam" \
#"us-east-1/citizen/sg" \
#"us-east-1/citizen/packer" \
#"us-east-1/citizen/ec2" \
#"us-east-1/citizen/ec2-configuration" \
#"us-east-1/citizen/dns" \
#"us-east-1/p-rep/keys" \
#"us-east-1/p-rep/iam" \
#"us-east-1/p-rep/sg" \
#"us-east-1/p-rep/packer" \
#"us-east-1/p-rep/ec2" \
#"us-east-1/p-rep/ec2-configuration" \
#"us-east-1/p-rep/dns" \
#"us-east-1/network/nlb-eip" \
#"us-east-1/sentry/packer" \
#"us-east-1/sentry/user-data" \
#"us-east-1/sentry/sg" \
#"us-east-1/sentry/asg" \
#"us-east-1/network/nlb" \
#"us-east-1/firewalls/lambda-sg-cron-t3" \
#"us-east-1/bots/rhizome-icon-node-monitor" \
)