#!/usr/bin/env bash

DIRECTORIES=( \
#"global/audit/s3-cloudtrail" \
#"global/audit/cloudtrail" \
#"us-east-1/eip/eip-main" \
#"us-east-1/network/vpc-main" \
#"us-east-1/network/vpc-mgmt" \
#"us-east-1/network/vpc-support" \
#"us-east-1/network/vpc-services" \
#"us-east-1/network/peering-main" \
#"us-east-1/network/peering-mgmt-services" \
#"us-east-1/network/peering-mgmt-support" \
#"us-east-1/network/peering-support-services" \
#"us-east-1/network/dns" \
#"us-east-1/network/dns-main" \
#"us-east-1/bastion/keys-bucket" \
#"us-east-1/bastion/keys-object" \
#"us-east-1/bastion/user-data" \
#"us-east-1/bastion/iam" \
#"us-east-1/bastion/sg" \
#"us-east-1/bastion/ec2" \
#"us-east-1/bastion/dns" \
#"us-east-1/consul/keys" \
#"us-east-1/consul/packer" \
#"us-east-1/consul/asg" \
#"us-east-1/consul/dns" \
#"us-east-1/services/ecr" \
#"us-east-1/services/sg" \
#"us-east-1/services/eks" \
#"us-east-1/citizen/keys" \
#"us-east-1/citizen/iam" \
#"us-east-1/nat-main/sg" \
#"us-east-1/nlb/sg" \
#"us-east-1/sentry/sg" \
#"us-east-1/prep/sg" \
#"us-east-1/citizen/sg" \
#"us-east-1/citizen/packer" \
#"us-east-1/citizen/ec2" \
#"us-east-1/citizen/ec2-configuration" \
#"us-east-1/citizen/dns" \
#"us-east-1/prep/keys" \
#"us-east-1/prep/iam" \
#"us-east-1/prep/packer" \
#"us-east-1/prep/user-data" \
#"us-east-1/prep/ec2" \
#"us-east-1/prep/ec2-configuration" \
#"us-east-1/prep/dns" \
"us-east-1/prep/user-data-1" \
"us-east-1/prep/ec2-1" \
"us-east-1/eip/eip-testnet-3" \
"us-east-1/prep/ec2-configuration-1" \
#"us-east-1/sentry/packer" \
#"us-east-1/sentry/user-data" \
#"us-east-1/sentry/asg" \
#"us-east-1/nlb/nlb-logging-bucket" \
#"us-east-1/nlb/nlb" \
#"us-east-1/nlb/dns" \
#"us-east-1/nat-main/ami" \
#"us-east-1/nat-main/user-data" \
#"us-east-1/nat-main/keys" \
#"us-east-1/nat-main/ec2" \
#"us-east-1/nat-main/ec2-configuration" \
#"us-east-1/nat-main/dns" \
#"us-east-1/firewalls/lambda-sg-cron-t3" \
#"us-east-1/bots/rhizome-icon-node-monitor" \
)