name: "c3"
stack:
  - "global/audit/s3-cloudtrail"
  - "global/audit/cloudtrail"
  - "us-east-1/logging/log-config-bucket"
  - "us-east-1/logging/lb-logging-bucket"
  - "us-east-1/data"
  - "us-east-1/network/vpc-main"
  - "us-east-1/network/dns-t1"
  - "us-east-1/prep/keys"
  - "us-east-1/prep/iam"
  - "us-east-1/prep/sg"
  - "us-east-1/prep/packer"
  - "us-east-1/prep/ec2"
  - "us-east-1/prep/ec2-configuration"
  - "us-east-1/prep/dns"
  - "us-east-1/firewalls/lambda-sg-cron-t3"
  - "us-east-1/bots/rhizome-icon-node-monitor"