name: "c3"
stack:
  - "global/audit/s3-cloudtrail"
  - "global/audit/cloudtrail"
  - "us-east-1/logging/log-config-bucket"
  - "us-east-1/logging/lb-logging-bucket"
  - "us-east-1/data"
  - "us-east-1/network/vpc-main"
  - "us-east-1/network/vpc-mgmt"
  - "us-east-1/network/peering-main-mgmt"
  - "us-east-1/network/dns-t2"
  - "us-east-1/bastion/keys-bucket"
  - "us-east-1/bastion/keys"
  - "us-east-1/bastion/iam"
  - "us-east-1/bastion/sg"
  - "us-east-1/bastion/ec2"
  - "us-east-1/bastion/dns"
  - "us-east-1/citizen/keys"
  - "us-east-1/citizen/iam"
  - "us-east-1/citizen/sg"
  - "us-east-1/citizen/packer"
  - "us-east-1/citizen/ec2"
  - "us-east-1/citizen/ec2-configuration"
  - "us-east-1/citizen/dns"
  - "us-east-1/prep/keys"
  - "us-east-1/prep/iam"
  - "us-east-1/prep/sg"
  - "us-east-1/prep/packer"
  - "us-east-1/prep/ec2"
  - "us-east-1/prep/ec2-configuration"
  - "us-east-1/prep/dns"
  - "us-east-1/firewalls/lambda-sg-cron-t3"
  - "us-east-1/bots/rhizome-icon-node-monitor"